/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSingleShipmentsRouteImport } from './routes/_authenticated/single-shipments'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedImportScheduleRouteImport } from './routes/_authenticated/import-schedule'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsolesRouteImport } from './routes/_authenticated/consoles'
import { Route as AuthenticatedClockRouteImport } from './routes/_authenticated/clock'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedVesselsTabRouteImport } from './routes/_authenticated/vessels.$tab'
import { Route as ApiPublicHooksTrackingReminderRouteImport } from './routes/api/public/hooks/tracking-reminder'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSingleShipmentsRoute =
  AuthenticatedSingleShipmentsRouteImport.update({
    id: '/single-shipments',
    path: '/single-shipments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportScheduleRoute =
  AuthenticatedImportScheduleRouteImport.update({
    id: '/import-schedule',
    path: '/import-schedule',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsolesRoute = AuthenticatedConsolesRouteImport.update({
  id: '/consoles',
  path: '/consoles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClockRoute = AuthenticatedClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVesselsTabRoute = AuthenticatedVesselsTabRouteImport.update({
  id: '/vessels/$tab',
  path: '/vessels/$tab',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksTrackingReminderRoute =
  ApiPublicHooksTrackingReminderRouteImport.update({
    id: '/api/public/hooks/tracking-reminder',
    path: '/api/public/hooks/tracking-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clock': typeof AuthenticatedClockRoute
  '/consoles': typeof AuthenticatedConsolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import-schedule': typeof AuthenticatedImportScheduleRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/single-shipments': typeof AuthenticatedSingleShipmentsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vessels/$tab': typeof AuthenticatedVesselsTabRoute
  '/api/public/hooks/tracking-reminder': typeof ApiPublicHooksTrackingReminderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clock': typeof AuthenticatedClockRoute
  '/consoles': typeof AuthenticatedConsolesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/import-schedule': typeof AuthenticatedImportScheduleRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/results': typeof AuthenticatedResultsRoute
  '/single-shipments': typeof AuthenticatedSingleShipmentsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vessels/$tab': typeof AuthenticatedVesselsTabRoute
  '/api/public/hooks/tracking-reminder': typeof ApiPublicHooksTrackingReminderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/clock': typeof AuthenticatedClockRoute
  '/_authenticated/consoles': typeof AuthenticatedConsolesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/import-schedule': typeof AuthenticatedImportScheduleRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/single-shipments': typeof AuthenticatedSingleShipmentsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vessels/$tab': typeof AuthenticatedVesselsTabRoute
  '/api/public/hooks/tracking-reminder': typeof ApiPublicHooksTrackingReminderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/archive'
    | '/audit'
    | '/clock'
    | '/consoles'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/import-schedule'
    | '/profile'
    | '/results'
    | '/single-shipments'
    | '/tasks'
    | '/users'
    | '/vessels/$tab'
    | '/api/public/hooks/tracking-reminder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alerts'
    | '/archive'
    | '/audit'
    | '/clock'
    | '/consoles'
    | '/dashboard'
    | '/help'
    | '/history'
    | '/import-schedule'
    | '/profile'
    | '/results'
    | '/single-shipments'
    | '/tasks'
    | '/users'
    | '/vessels/$tab'
    | '/api/public/hooks/tracking-reminder'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alerts'
    | '/_authenticated/archive'
    | '/_authenticated/audit'
    | '/_authenticated/clock'
    | '/_authenticated/consoles'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/history'
    | '/_authenticated/import-schedule'
    | '/_authenticated/profile'
    | '/_authenticated/results'
    | '/_authenticated/single-shipments'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/_authenticated/vessels/$tab'
    | '/api/public/hooks/tracking-reminder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksTrackingReminderRoute: typeof ApiPublicHooksTrackingReminderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/single-shipments': {
      id: '/_authenticated/single-shipments'
      path: '/single-shipments'
      fullPath: '/single-shipments'
      preLoaderRoute: typeof AuthenticatedSingleShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-schedule': {
      id: '/_authenticated/import-schedule'
      path: '/import-schedule'
      fullPath: '/import-schedule'
      preLoaderRoute: typeof AuthenticatedImportScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consoles': {
      id: '/_authenticated/consoles'
      path: '/consoles'
      fullPath: '/consoles'
      preLoaderRoute: typeof AuthenticatedConsolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clock': {
      id: '/_authenticated/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof AuthenticatedClockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vessels/$tab': {
      id: '/_authenticated/vessels/$tab'
      path: '/vessels/$tab'
      fullPath: '/vessels/$tab'
      preLoaderRoute: typeof AuthenticatedVesselsTabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/tracking-reminder': {
      id: '/api/public/hooks/tracking-reminder'
      path: '/api/public/hooks/tracking-reminder'
      fullPath: '/api/public/hooks/tracking-reminder'
      preLoaderRoute: typeof ApiPublicHooksTrackingReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedClockRoute: typeof AuthenticatedClockRoute
  AuthenticatedConsolesRoute: typeof AuthenticatedConsolesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImportScheduleRoute: typeof AuthenticatedImportScheduleRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedSingleShipmentsRoute: typeof AuthenticatedSingleShipmentsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVesselsTabRoute: typeof AuthenticatedVesselsTabRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedClockRoute: AuthenticatedClockRoute,
  AuthenticatedConsolesRoute: AuthenticatedConsolesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImportScheduleRoute: AuthenticatedImportScheduleRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedSingleShipmentsRoute: AuthenticatedSingleShipmentsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVesselsTabRoute: AuthenticatedVesselsTabRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksTrackingReminderRoute: ApiPublicHooksTrackingReminderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
